const PDFDocument = require("pdfkit");
const AttendanceSession = require("../models/AttendanceSession");
const AttendanceRecord = require("../models/AttendanceRecord");
const Course = require("../models/Course");
const Student = require("../models/Student");

const drawLine = (doc) => {
  doc
    .strokeColor("#e4e4e7")
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(550, doc.y)
    .stroke();
  doc.moveDown(0.5);
};

const drawHeader = (doc, title, subtitle = "") => {
  doc
    .fillColor("#4f46e5")
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("QRoll Attendance System", 50, 50);

  doc
    .fillColor("#71717a")
    .fontSize(10)
    .font("Helvetica")
    .text("HND Computer Science — Automated Attendance Report", 50, 75);

  doc.moveDown(1);
  drawLine(doc);

  doc
    .fillColor("#18181b")
    .fontSize(16)
    .font("Helvetica-Bold")
    .text(title, 50, doc.y);

  if (subtitle) {
    doc
      .fillColor("#71717a")
      .fontSize(10)
      .font("Helvetica")
      .text(subtitle, 50, doc.y + 5);
  }

  doc.moveDown(1);
  drawLine(doc);
};

const drawFooter = (doc) => {
  const bottom = doc.page.height - 50;
  doc
    .fillColor("#71717a")
    .fontSize(9)
    .font("Helvetica")
    .text(
      `Generated by QRoll on ${new Date().toLocaleString()}`,
      50,
      bottom,
      { align: "left" }
    )
    .text("Confidential — For Internal Use Only", 50, bottom, {
      align: "right",
    });
};

// ─────────────────────────────────────────
// REPORT 1: Session Report
// ─────────────────────────────────────────
const generateSessionReport = async (res, sessionId) => {
  const session = await AttendanceSession.findById(sessionId)
    .populate("course", "name courseCode")
    .populate({
      path: "lecturer",
      populate: { path: "user", select: "fullName" },
    });

  if (!session) throw new Error("Session not found");

  // Populate student → then student.user for fullName
  const records = await AttendanceRecord.find({ session: sessionId })
    .populate({
      path: "student",
      select: "studentId level",
      populate: { path: "user", select: "fullName" },
    });

  const presentRecords = records.filter((r) => r.status === "present");
  const absentRecords = records.filter((r) => r.status === "absent");
  const totalStudents = records.length;
  const attendanceRate =
    totalStudents > 0
      ? Math.round((presentRecords.length / totalStudents) * 100)
      : 0;

  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="session-report-${sessionId}.pdf"`
  );
  doc.pipe(res);

  drawHeader(
    doc,
    "Session Attendance Report",
    `${session.course?.courseCode} — ${session.course?.name}`
  );

  // Session info
  const lecturerName = session.lecturer?.user?.fullName || "N/A";
  const info = [
    ["Course", `${session.course?.courseCode} — ${session.course?.name}`],
    ["Lecturer", lecturerName],
    ["Topic", session.topic || "N/A"],
    ["Date", new Date(session.createdAt).toLocaleDateString()],
    ["Status", session.status?.toUpperCase()],
    ["Total Students", totalStudents],
    ["Present", presentRecords.length],
    ["Absent", absentRecords.length],
    ["Attendance Rate", `${attendanceRate}%`],
  ];

  info.forEach(([label, value]) => {
    doc
      .fillColor("#71717a")
      .fontSize(10)
      .font("Helvetica-Bold")
      .text(`${label}: `, 50, doc.y, { continued: true })
      .fillColor("#18181b")
      .font("Helvetica")
      .text(String(value));
  });

  doc.moveDown(1);
  drawLine(doc);

  // ── Present Students ──
  doc
    .fillColor("#10b981")
    .fontSize(12)
    .font("Helvetica-Bold")
    .text(`✓ Present Students (${presentRecords.length})`, 50, doc.y);
  doc.moveDown(0.5);

  if (presentRecords.length === 0) {
    doc
      .fillColor("#71717a")
      .fontSize(10)
      .font("Helvetica")
      .text("No students marked present.", 50, doc.y);
  } else {
    doc.fillColor("#4f46e5").fontSize(10).font("Helvetica-Bold");
    doc.text("S/N", 50, doc.y, { width: 40 });
    doc.text("Name", 90, doc.y - 12, { width: 180 });
    doc.text("Matric No.", 270, doc.y - 12, { width: 120 });
    doc.text("Level", 390, doc.y - 12, { width: 60 });
    doc.text("Scan Time", 450, doc.y - 12, { width: 100 });
    doc.moveDown(0.3);
    drawLine(doc);

    presentRecords.forEach((record, index) => {
      const s = record.student;
      const fullName = s?.user?.fullName || "Unknown";
      const y = doc.y;
      doc.fillColor("#18181b").fontSize(9).font("Helvetica");
      doc.text(String(index + 1), 50, y, { width: 40 });
      doc.text(fullName, 90, y, { width: 180 });
      doc.text(s?.studentId || "N/A", 270, y, { width: 120 });
      doc.text(s?.level || "N/A", 390, y, { width: 60 });
      doc.text(
        record.scannedAt
          ? new Date(record.scannedAt).toLocaleTimeString()
          : "N/A",
        450,
        y,
        { width: 100 }
      );
      doc.moveDown(0.4);
    });
  }

  doc.moveDown(1);
  drawLine(doc);

  // ── Absent Students ──
  doc
    .fillColor("#f43f5e")
    .fontSize(12)
    .font("Helvetica-Bold")
    .text(`✗ Absent Students (${absentRecords.length})`, 50, doc.y);
  doc.moveDown(0.5);

  if (absentRecords.length === 0) {
    doc
      .fillColor("#71717a")
      .fontSize(10)
      .font("Helvetica")
      .text("No students absent.", 50, doc.y);
  } else {
    doc.fillColor("#4f46e5").fontSize(10).font("Helvetica-Bold");
    doc.text("S/N", 50, doc.y, { width: 40 });
    doc.text("Name", 90, doc.y - 12, { width: 180 });
    doc.text("Matric No.", 270, doc.y - 12, { width: 120 });
    doc.text("Level", 390, doc.y - 12, { width: 60 });
    doc.moveDown(0.3);
    drawLine(doc);

    absentRecords.forEach((record, index) => {
      const s = record.student;
      const fullName = s?.user?.fullName || "Unknown";
      const y = doc.y;
      doc.fillColor("#18181b").fontSize(9).font("Helvetica");
      doc.text(String(index + 1), 50, y, { width: 40 });
      doc.text(fullName, 90, y, { width: 180 });
      doc.text(s?.studentId || "N/A", 270, y, { width: 120 });
      doc.text(s?.level || "N/A", 390, y, { width: 60 });
      doc.moveDown(0.4);
    });
  }

  drawFooter(doc);
  doc.end();
};

// ─────────────────────────────────────────
// REPORT 2: Course Report
// ─────────────────────────────────────────
const generateCourseReport = async (res, courseId, startDate, endDate) => {
  const course = await Course.findById(courseId);
  if (!course) throw new Error("Course not found");

  const query = { course: courseId };
  if (startDate && endDate) {
    query.createdAt = {
      $gte: new Date(startDate),
      $lte: new Date(endDate),
    };
  }

  const sessions = await AttendanceSession.find(query).sort({ createdAt: -1 });

  const sessionData = await Promise.all(
    sessions.map(async (session) => {
      const records = await AttendanceRecord.find({ session: session._id });
      const present = records.filter((r) => r.status === "present").length;
      const total = records.length;
      const rate = total > 0 ? Math.round((present / total) * 100) : 0;
      return { session, present, total, rate };
    })
  );

  const overallPresent = sessionData.reduce((sum, s) => sum + s.present, 0);
  const overallTotal = sessionData.reduce((sum, s) => sum + s.total, 0);
  const overallRate =
    overallTotal > 0
      ? Math.round((overallPresent / overallTotal) * 100)
      : 0;

  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="course-report-${courseId}.pdf"`
  );
  doc.pipe(res);

  drawHeader(
    doc,
    "Course Attendance Report",
    `${course.courseCode} — ${course.courseTitle}`
  );

  const info = [
    ["Course Code", course.courseCode],
    ["Course Name", course.courseTitle],
    ["Total Sessions", sessions.length],
    ["Overall Attendance Rate", `${overallRate}%`],
  ];

  info.forEach(([label, value]) => {
    doc
      .fillColor("#71717a")
      .fontSize(10)
      .font("Helvetica-Bold")
      .text(`${label}: `, 50, doc.y, { continued: true })
      .fillColor("#18181b")
      .font("Helvetica")
      .text(String(value));
  });

  doc.moveDown(1);
  drawLine(doc);

  doc
    .fillColor("#18181b")
    .fontSize(12)
    .font("Helvetica-Bold")
    .text("Session Breakdown", 50, doc.y);
  doc.moveDown(0.5);

  doc.fillColor("#4f46e5").fontSize(10).font("Helvetica-Bold");
  doc.text("S/N", 50, doc.y, { width: 35 });
  doc.text("Topic", 85, doc.y - 12, { width: 160 });
  doc.text("Date", 245, doc.y - 12, { width: 90 });
  doc.text("Present", 335, doc.y - 12, { width: 65 });
  doc.text("Total", 400, doc.y - 12, { width: 55 });
  doc.text("Rate", 455, doc.y - 12, { width: 60 });
  doc.text("Status", 515, doc.y - 12, { width: 60 });
  doc.moveDown(0.3);
  drawLine(doc);

  sessionData.forEach(({ session, present, total, rate }, index) => {
    const y = doc.y;
    const rateColor = rate >= 75 ? "#10b981" : "#f43f5e";

    doc.fillColor("#18181b").fontSize(9).font("Helvetica");
    doc.text(String(index + 1), 50, y, { width: 35 });
    doc.text(session.topic || "N/A", 85, y, { width: 160 });
    doc.text(
      new Date(session.createdAt).toLocaleDateString(),
      245,
      y,
      { width: 90 }
    );
    doc.text(String(present), 335, y, { width: 65 });
    doc.text(String(total), 400, y, { width: 55 });
    doc.fillColor(rateColor).text(`${rate}%`, 455, y, { width: 60 });
    doc
      .fillColor("#18181b")
      .text(session.status?.toUpperCase() || "N/A", 515, y, { width: 60 });
    doc.moveDown(0.4);
  });

  drawFooter(doc);
  doc.end();
};

// ─────────────────────────────────────────
// REPORT 3: Student Report
// ─────────────────────────────────────────
const generateStudentReport = async (res, studentId) => {
  const student = await Student.findById(studentId)
    .populate("user", "fullName")
    .populate("enrolledCourses", "name courseTitle");

  if (!student) throw new Error("Student not found");

  const courseData = await Promise.all(
    (student.enrolledCourses || []).map(async (course) => {
      const sessions = await AttendanceSession.find({
        course: course._id,
        status: "closed",
      });
      const sessionIds = sessions.map((s) => s._id);
      const totalSessions = sessions.length;
      const presentCount = await AttendanceRecord.countDocuments({
        session: { $in: sessionIds },
        student: studentId,
        status: "present",
      });
      const rate =
        totalSessions > 0
          ? Math.round((presentCount / totalSessions) * 100)
          : 0;
      return { course, totalSessions, presentCount, rate };
    })
  );

  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="student-report-${studentId}.pdf"`
  );
  doc.pipe(res);

  const fullName = student.user?.fullName || "Unknown Student";

  drawHeader(
    doc,
    "Student Attendance Report",
    `${fullName} — ${student.studentId}`
  );

  const info = [
    ["Full Name", fullName],
    ["Student ID", student.studentId || "N/A"],
    ["Level", student.level || "N/A"],
    ["Department", student.department || "N/A"],
  ];

  info.forEach(([label, value]) => {
    doc
      .fillColor("#71717a")
      .fontSize(10)
      .font("Helvetica-Bold")
      .text(`${label}: `, 50, doc.y, { continued: true })
      .fillColor("#18181b")
      .font("Helvetica")
      .text(String(value));
  });

  doc.moveDown(1);
  drawLine(doc);

  doc
    .fillColor("#18181b")
    .fontSize(12)
    .font("Helvetica-Bold")
    .text("Course Attendance Breakdown", 50, doc.y);
  doc.moveDown(0.5);

  doc.fillColor("#4f46e5").fontSize(10).font("Helvetica-Bold");
  doc.text("S/N", 50, doc.y, { width: 35 });
  doc.text("Course Code", 85, doc.y - 12, { width: 100 });
  doc.text("Course Name", 185, doc.y - 12, { width: 180 });
  doc.text("Sessions", 365, doc.y - 12, { width: 70 });
  doc.text("Present", 435, doc.y - 12, { width: 65 });
  doc.text("Rate", 500, doc.y - 12, { width: 60 });
  doc.moveDown(0.3);
  drawLine(doc);

  courseData.forEach(({ course, totalSessions, presentCount, rate }, index) => {
    const y = doc.y;
    const rateColor = rate >= 75 ? "#10b981" : "#f43f5e";

    doc.fillColor("#18181b").fontSize(9).font("Helvetica");
    doc.text(String(index + 1), 50, y, { width: 35 });
    doc.text(course.courseCode || "N/A", 85, y, { width: 100 });
    doc.text(course.courseTitle || "N/A", 185, y, { width: 180 });
    doc.text(String(totalSessions), 365, y, { width: 70 });
    doc.text(String(presentCount), 435, y, { width: 65 });
    doc.fillColor(rateColor).text(`${rate}%`, 500, y, { width: 60 });
    doc.moveDown(0.4);
  });

  drawFooter(doc);
  doc.end();
};

module.exports = {
  generateSessionReport,
  generateCourseReport,
  generateStudentReport,
};